### PR TITLE
Consider categories on test fixtures in test list

### LINKED ISSUE #181: Categories on test fixtures not considered in test list
I use the `CategoryAttribute` on individual test cases. When all test cases of a test fixture belong to a specific category, I place the `CategoryAttribute` right on the test fixture.
I expect this to be functionally equivalent as if I had marked each test case, when dealing with test cases.

However, in the test list view, when grouping by categories, categories defined by means of the test fixtures are not considered.

The following code:
```C#
[Category("a")]
public class A
{
    [Test]
    public void A1() {
    }

    [Test]
    public void A2()
    {
    }
}

public class B
{
    [Test]
    [Category("a")]
    public void B1()
    {
    }

    [Test]
    [Category("a")]
    public void B2()
    {
    }
}
```
produces this grouping: 
this

I'd expect A1 and A2 to appear under the category `a`.

I should be able to make a PR for this.

### PR DESCRIPTION
**Pull request by chm-tm**
Resolves TestCentric/testcentric-gui#238

### CODE REVIEW

**Comment by immeraufdemhund** [comment]
Although the change itself is simple enough, the pull request shows 3 commits, and a single file change. Could you please rebase?

**Comment by CharliePoole** [comment]
@immeraufdemhund We shouldn't ask him rebase until we know we want to implement this. I marked the issue as design, meaning "we need to decide how we want it to work." :-)

**Comment by chm-tm** [comment]
@immeraufdemhund Thanks for your offering. Unfortunately, I didn't actually have time so far to learn Git. So, I decided to defer cleaning up until you wanted to merge that PR, which I didn't expect in the near future.

@CharliePoole I think you forgot to actually mark this issue as design.

BTW, congratulations to land on the [.NET poster](https://www.microsoft.com/net/images/dotNET_poster.pdf).

**Comment by CharliePoole** [comment]
@chm-tm It's the issue (#181) that gets marked and labelled, not the PR. Thanks for pointing out the poster to me!

**Comment by CharliePoole** [comment]
Now that I moved the experimental gui into the testcentric-gui project and restructured things, this PR is orphaned. I'll look it over and figure out what to do in the next few weeks.

**Comment by CharliePoole** [comment]
Closing this PR, which has been replaced by TestCentric/testcentric-gui#249

**Pull request closed without merging**
